### ISSUE TITLE
Background of main-page 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#7] opened 2020-12-24 07:10 UTC
Beautify the background of main page using particle js-effects . 
Reference : https://codepen.io/natewiley/pen/GgONKy

**Comment by BharatiSukanya** [comment] 2020-12-24 17:03
@ankitapuri Can I work on this issue?

**Comment by ankitapuri** [comment] 2020-12-24 17:33
> @ankitapuri Can I work on this issue?

sure!

**Comment by Harshit850** [comment] 2020-12-29 15:03
I would love to suggest you a beautiful background, May I?

**Comment by BharatiSukanya** [comment] 2020-12-29 15:07
@Harshit850 Sure , go ahead.

**Comment by Harshit850** [comment] 2020-12-29 17:53
Done @BharatiSukanya

**Comment by iamkrati22** [comment] 2021-02-26 17:27
Is this issue still open? If yes, can I work on this as a part of gssoc'21? :)

**Comment by Nikhita28** [comment] 2021-03-08 12:14
I would like to work on this as a part of GSSoC '21 if the issue is still open

**Comment by ankitapuri** [comment] 2021-03-08 14:01
> I would like to work on this as a part of GSSoC '21 if the issue is still open

Sure you can .

**Comment by sahildotexe** [comment] 2021-03-09 03:39
Hey !! I 'm a participant of GSSOC'21, can you assign this issue to me?

**Comment by ankitapuri** [comment] 2021-03-09 03:53
> Hey !! I 'm a participant of GSSOC'21, can you assign this issue to me?

@Nikhita28 and @sahildotexe you both can co-ordinate together and make a PR accordingly .

**Comment by sahildotexe** [comment] 2021-03-09 05:10
Ok sure

**Comment by machine-sg** [comment] 2021-03-09 05:21
I am a GSSOC'21 participant and I wish to work on this.  Hope to hear back from you . 
Thank you .

**Comment by Nikhita28** [comment] 2021-03-09 06:12
@sahildotexe where can we discuss this?
https://www.linkedin.com/in/v-nikhita-5463701ba/ This is my LinkedIn. Maybe we could have a discussion over there.

**Comment by sahildotexe** [comment] 2021-03-09 06:26
Yeah will Ping you there

**Comment by Aarti002** [comment] 2021-03-09 13:01
Hey  @ankitapuri can i work on this issue if it is not done yet, as a GSSoC participant.

**Comment by simranbhalla3** [comment] 2021-03-11 10:12
i want to work on this issue if its not done yet , as a gssoc participant , please assign it to me @ankitapuri

**Comment by VishalPatil18** [comment] 2021-03-11 11:05
Hey @ankitapuri, Vishal here and would love to work with @sahildotexe and @Nikhita28 on this issue under GSSoC'21.
You can check my portfolio site https://spectevil.github.io to get an idea of my previous works and assign it to me if possible. As this is a major task 3 people working efficiently and fast will make this happen ASAP.
Thanks!

**Comment by ankitapuri** [comment] 2021-03-11 11:56
> Hey @ankitapuri, Vishal here and would love to work with @sahildotexe and @Nikhita28 on this issue under GSSoC'21.
> You can check my portfolio site https://spectevil.github.io to get an idea of my previous works and assign it to me if possible. As this is a major task 3 people working efficiently and fast will make this happen ASAP.
> Thanks!

Your portfolio is amazing but this issue is nearly done

**Comment by VishalPatil18** [comment] 2021-03-11 11:59
> > Hey @ankitapuri, Vishal here and would love to work with @sahildotexe and @Nikhita28 on this issue under GSSoC'21.
> > You can check my portfolio site https://spectevil.github.io to get an idea of my previous works and assign it to me if possible. As this is a major task 3 people working efficiently and fast will make this happen ASAP.
> > Thanks!
> 
> Your portfolio is amazing but this issue is nearly done

Ok, No worries! Thank You for your compliment!

**Closed as completed** 2021-03-13 16:55 UTC
Labels: enhancement, gssoc21, assigned, Level3
